# Imports

In [4]:
# %% [code]
import os
import pandas as pd
import numpy as np
import random
import traceback
from pathlib import Path

# Importando funções necessárias
# Agora, importamos o novo reader "read_hiacc" em vez de "read_newdataset"
from teste import read_hiacc_smartphone

# Pipelines e mapeamento de colunas (aqui consideramos que o novo dataset utiliza a chave "HIAAC")
from pipelines import pipelines, match_columns

# Funções de balanceamento e split
from steps import (
    SplitGuaranteeingAllClassesPerSplit,
    BalanceToMinimumClass,
    BalanceToMinimumClassAndUser,
    FilterByCommonRows,
)

# Configura seeds para reprodutibilidade
np.random.seed(42)
random.seed(42)

## Paths

In [5]:

# Define o caminho raiz para o novo dataset
root_path = "/home/maria/git/DAGHAR/data/original/HIAAC"

# Define o path de saída
output_path = "/home/maria/git/DAGHAR/Dataset_v3/Data_processed"

# Processing

In [6]:
# %% [code]
# --- Leitura dos dados brutos ---
print("Lendo os dados raw do novo dataset HIACC...")
# Aqui, usamos o novo reader
df_root, df = read_hiacc_smartphone(root_path)

Lendo os dados raw do novo dataset HIACC...
Iniciando leitura do dataset HIACC...
Processamento concluído.

In [7]:
df_root

,timestamp-server-accel,accel-x,accel-y,accel-z,user,pos,trial,activity code,timestamp-server-gyro,gyro-x,gyro-y,gyro-z,user
0,0,0.531513,-9.809343,-0.404620,1,Bolso_direito,0,0,0,0.011988,0.003207,0.010156,1
1,9,0.531513,-9.838074,-0.414197,1,Bolso_direito,0,0,9,0.010767,0.000764,0.012599,1
2,17,0.529119,-9.838074,-0.423774,1,Bolso_direito,0,0,21,0.013210,-0.005345,0.015653,1
3,28,0.577003,-9.828497,-0.359130,1,Bolso_direito,0,0,31,0.015043,-0.008399,0.015043,1
4,39,0.588974,-9.826103,-0.318429,1,Bolso_direito,0,0,42,0.024816,-0.009010,0.016264,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
197995,1000054,-9.708787,0.440533,1.173159,1,Mochila,329,-1,1000593,0.189139,-0.040928,0.022373,1
197996,1000061,-9.742306,0.474052,1.170765,1,Mochila,329,-1,1000602,0.189750,-0.031154,0.035201,1
197997,1000067,-9.766248,0.512359,1.130063,1,Mochila,329,-1,1000607,0.195859,-0.020769,0.036423,1
197998,1000084,-9.814132,0.648829,1.091756,1,Mochila,329,-1,1000621,0.196470,-0.032376,0.027260,1
197999,1000093,-9.857227,0.699107,1.046266,1,Mochila,329,-1,1000631,0.179365,-0.017104,0.024816,1

In [8]:
df[0].head()

,timestamp-server-accel,accel-x,accel-y,accel-z,user,pos,trial,activity code,timestamp-server-gyro,gyro-x,gyro-y,gyro-z,user
0,0,0.531513,-9.809343,-0.404620,1,Bolso_direito,0,0,0,0.011988,0.003207,0.010156,1
1,9,0.531513,-9.838074,-0.414197,1,Bolso_direito,0,0,9,0.010767,0.000764,0.012599,1
2,17,0.529119,-9.838074,-0.423774,1,Bolso_direito,0,0,21,0.013210,-0.005345,0.015653,1
3,28,0.577003,-9.828497,-0.359130,1,Bolso_direito,0,0,31,0.015043,-0.008399,0.015043,1
4,39,0.588974,-9.826103,-0.318429,1,Bolso_direito,0,0,42,0.024816,-0.009010,0.016264,1